# Server config
server.port=${SERVER_PORT:8081}

# Database config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# Password sẽ được load từ Secrets Manager qua AwsSecretsConfig
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Redis config (cho WebSocket Multi-node)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379

# AWS config
aws.s3.bucket=${AWS_S3_BUCKET}
aws.region=${AWS_REGION:us-east-1}
aws.secrets.arn=${SECRET_ARN}

# App Config
jwt.secret=${JWT_SECRET:YourSuperSecretKeyForJwtAuthenticationWhichShouldBeLongEnough}
