# Server config
server.port=${SERVER_PORT:8081}

# Database config - FIX DỨT ĐIỂM BẰNG CÁCH THÊM URL THẬT LÀM MẶC ĐỊNH
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://chatapp-nexus-db.cdau8omekqbf.ap-southeast-1.rds.amazonaws.com:5432/chatappdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dbadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YourSecurePassword123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis config
spring.data.redis.host=${REDIS_HOST:chatapp-nexus-redis.gaj569.0001.apse1.cache.amazonaws.com}
spring.data.redis.port=6379

# AWS config
aws.s3.bucket=${AWS_S3_BUCKET:chatapp-nexus-uploads}
aws.region=${AWS_REGION:ap-southeast-1}
aws.secrets.arn=${SECRET_ARN}

# App Config
jwt.secret=${JWT_SECRET:YourSuperSecretKeyForJwtAuthenticationWhichShouldBeLongEnough}
jwt.expiration=${JWT_EXPIRATION:86400000}
