name: Android CI/CD Build

on:
  push:
    branches: [ "main" ]
    paths: [ "chatapp_mobile/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x chatapp_mobile/gradlew

      - name: Build with Gradle
        env:
          # ✅ TRUYỀN DNS CỦA ALB VÀO BIẾN MÔI TRƯỜNG
          # Khi build APK, Gradle sẽ tự động nhúng địa chỉ này vào code
          MOBILE_BASE_URL: http://${{ secrets.ALB_DNS_NAME }}/
        run: |
          cd chatapp_mobile
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatapp-debug
          path: chatapp_mobile/app/build/outputs/apk/debug/app-debug.apk
